server {
    listen       80;
    server_name  _;

    root  /usr/share/nginx/html;

    index index.html story.html;

    location / {
        try_files $uri $uri.html $uri/ =404;
    }

    location /story_files/ {
        expires 1h;
        add_header Cache-Control "public";
    }
}
